# Generated by Django 6.0.4 on 2026-05-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm10', models.FloatField(verbose_name='PM10')),
                ('pm2_5', models.FloatField(verbose_name='PM2.5')),
                ('carbon_monoxide', models.FloatField(verbose_name='Carbon Monoxide')),
                ('nitrogen_dioxide', models.FloatField(verbose_name='Nitrogen Dioxide')),
                ('sulphur_dioxide', models.FloatField(verbose_name='Sulphur Dioxide')),
                ('ozone', models.FloatField(verbose_name='Ozone')),
                ('dust', models.FloatField(verbose_name='Dust')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
                ('precipitation', models.FloatField(verbose_name='Precipitation')),
                ('wind_speed', models.FloatField(verbose_name='Wind Speed')),
                ('pressure', models.FloatField(verbose_name='Pressure')),
                ('aqi_category', models.CharField(default='Good', max_length=100, verbose_name='AQI Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Air Quality Record',
                'verbose_name_plural': 'Air Quality Records',
                'ordering': ['-id'],
            },
        ),
    ]
