# Generated by Django 6.0.4 on 2026-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirQualityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.FloatField(help_text='Composite air quality index value.', verbose_name='Air Quality Index (AQI)')),
                ('pm10', models.FloatField(help_text='Particulate matter <= 10 micrometres (ug/m3).', verbose_name='PM10')),
                ('pm2_5', models.FloatField(help_text='Particulate matter <= 2.5 micrometres (ug/m3).', verbose_name='PM2.5')),
                ('no2', models.FloatField(help_text='Nitrogen dioxide concentration (ppb).', verbose_name='NO2')),
                ('so2', models.FloatField(help_text='Sulphur dioxide concentration (ppb).', verbose_name='SO2')),
                ('o3', models.FloatField(help_text='Ground-level ozone concentration (ppb).', verbose_name='O3')),
                ('temperature', models.FloatField(help_text='Ambient temperature (Celsius).', verbose_name='Temperature')),
                ('humidity', models.FloatField(help_text='Relative humidity (%).', verbose_name='Humidity')),
                ('wind_speed', models.FloatField(help_text='Wind speed (m/s).', verbose_name='Wind Speed')),
                ('respiratory_cases', models.IntegerField(help_text='Number of respiratory cases reported.', verbose_name='Respiratory Cases')),
                ('cardiovascular_cases', models.IntegerField(help_text='Number of cardiovascular cases reported.', verbose_name='Cardiovascular Cases')),
                ('hospital_admissions', models.IntegerField(help_text='Number of hospital admissions.', verbose_name='Hospital Admissions')),
                ('health_impact_score', models.FloatField(help_text='Composite health impact score (0-100).', verbose_name='Health Impact Score')),
                ('health_impact_class', models.IntegerField(choices=[(0, 'Good - No health impact'), (1, 'Moderate - Minor irritation possible'), (2, 'Unhealthy for Sensitive Groups'), (3, 'Unhealthy - Significant risk'), (4, 'Hazardous - Emergency conditions')], default=0, help_text='Predicted class: 0=Good, 1=Moderate, 2=Unhealthy-Sensitive, 3=Unhealthy, 4=Hazardous.', verbose_name='Health Impact Class')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Air Quality Record',
                'verbose_name_plural': 'Air Quality Records',
                'ordering': ['-id'],
            },
        ),
    ]
