# Generated by Django 6.0.4 on 2026-05-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airqualityrecord',
            options={},
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='month_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='aqi_category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='carbon_monoxide',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='dust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='nitrogen_dioxide',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='ozone',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm10',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm2_5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='precipitation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='sulphur_dioxide',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
