# Generated by Django 6.0.4 on 2026-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_alter_airqualityrecord_options_airqualityrecord_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
