# Generated by Django 6.0.4 on 2026-05-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_airqualityrecord_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='airqualityrecord',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='is_weekend',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='wind_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airqualityrecord',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
