# Generated by Django 6.0.4 on 2026-05-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_airqualityrecord_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
