# Generated by Django 6.0.4 on 2026-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0005_alter_airqualityrecord_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airqualityrecord',
            name='carbon_monoxide',
            field=models.FloatField(verbose_name='Carbon Monoxide (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='dust',
            field=models.FloatField(verbose_name='Dust (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='humidity',
            field=models.FloatField(verbose_name='Humidity (%)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='nitrogen_dioxide',
            field=models.FloatField(verbose_name='Nitrogen Dioxide (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='ozone',
            field=models.FloatField(verbose_name='Ozone (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm10',
            field=models.FloatField(verbose_name='PM10 (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pm2_5',
            field=models.FloatField(verbose_name='PM2.5 (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='precipitation',
            field=models.FloatField(verbose_name='Precipitation (mm)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='pressure',
            field=models.FloatField(verbose_name='Pressure (hPa)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='sulphur_dioxide',
            field=models.FloatField(verbose_name='Sulphur Dioxide (µg/m³)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='temperature',
            field=models.FloatField(verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='wind_direction',
            field=models.FloatField(blank=True, null=True, verbose_name='Wind Direction (°)'),
        ),
        migrations.AlterField(
            model_name='airqualityrecord',
            name='wind_speed',
            field=models.FloatField(verbose_name='Wind Speed (m/s)'),
        ),
    ]
